### ISSUE TITLE
Names collisions with standart libs

### ISSUE THREAD

**Issue by Oplkill** [KeithGDR/sm-resources#2]
Some name collisions with standart libs, which included in latest sourcemod. 
I understand, that they have different behavior, but many plugins using them, so it leads to compile errors.

Function: "**SetEntityOwner**" have the same name as in lib "**sdktools-functions.inc**"
Function: "**DispatchKeyValueInt**" have the same name as in lib "**sdktools-functions.inc**"
Function: "**SetEntityCollisionGroup**" have the same name as in lib "**sdktools-functions.inc**"
Function: "**GetCmdArgInt**" have the same name as in lib "**console.inc**"
Function: "**GetCmdArgFloat**" have the same name as in lib "**console.inc**"

**Comment by KeithGDR** [comment]
They all effectively do the same thing so they can be disabled and marked as deprecated.
